name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: .node-version
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Check
        run: pnpm run check

      - name: Test
        run: pnpm run test:cover

      - name: Build
        run: pnpm run build

      # Uncomment this step if you want to upload coverage reports to Codecov
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: mys1024/starter-node
